// Generated by gencpp from file autosense_msgs/TrackingFixedTrajectoryArray.msg
// DO NOT EDIT!


#ifndef AUTOSENSE_MSGS_MESSAGE_TRACKINGFIXEDTRAJECTORYARRAY_H
#define AUTOSENSE_MSGS_MESSAGE_TRACKINGFIXEDTRAJECTORYARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace autosense_msgs
{
template <class ContainerAllocator>
struct TrackingFixedTrajectoryArray_
{
  typedef TrackingFixedTrajectoryArray_<ContainerAllocator> Type;

  TrackingFixedTrajectoryArray_()
    : header()
    , ids()
    , periods()  {
    }
  TrackingFixedTrajectoryArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ids(_alloc)
    , periods(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _ids_type;
  _ids_type ids;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _periods_type;
  _periods_type periods;





  typedef boost::shared_ptr< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrackingFixedTrajectoryArray_

typedef ::autosense_msgs::TrackingFixedTrajectoryArray_<std::allocator<void> > TrackingFixedTrajectoryArray;

typedef boost::shared_ptr< ::autosense_msgs::TrackingFixedTrajectoryArray > TrackingFixedTrajectoryArrayPtr;
typedef boost::shared_ptr< ::autosense_msgs::TrackingFixedTrajectoryArray const> TrackingFixedTrajectoryArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator1> & lhs, const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ids == rhs.ids &&
    lhs.periods == rhs.periods;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator1> & lhs, const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autosense_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15c4ac76616716bf5251b2bb0d881bd6";
  }

  static const char* value(const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15c4ac76616716bfULL;
  static const uint64_t static_value2 = 0x5251b2bb0d881bd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autosense_msgs/TrackingFixedTrajectoryArray";
  }

  static const char* value(const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"# tracker id, all data relates in order\n"
"uint32[] ids\n"
"float64[] periods\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ids);
      stream.next(m.periods);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackingFixedTrajectoryArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autosense_msgs::TrackingFixedTrajectoryArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "periods[]" << std::endl;
    for (size_t i = 0; i < v.periods.size(); ++i)
    {
      s << indent << "  periods[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.periods[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOSENSE_MSGS_MESSAGE_TRACKINGFIXEDTRAJECTORYARRAY_H
