// Generated by gencpp from file water_msgs/ShipState.msg
// DO NOT EDIT!


#ifndef WATER_MSGS_MESSAGE_SHIPSTATE_H
#define WATER_MSGS_MESSAGE_SHIPSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gazebo_msgs/ModelState.h>

namespace water_msgs
{
template <class ContainerAllocator>
struct ShipState_
{
  typedef ShipState_<ContainerAllocator> Type;

  ShipState_()
    : header()
    , modelstate()  {
    }
  ShipState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , modelstate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::gazebo_msgs::ModelState_<ContainerAllocator>  _modelstate_type;
  _modelstate_type modelstate;





  typedef boost::shared_ptr< ::water_msgs::ShipState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::water_msgs::ShipState_<ContainerAllocator> const> ConstPtr;

}; // struct ShipState_

typedef ::water_msgs::ShipState_<std::allocator<void> > ShipState;

typedef boost::shared_ptr< ::water_msgs::ShipState > ShipStatePtr;
typedef boost::shared_ptr< ::water_msgs::ShipState const> ShipStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::water_msgs::ShipState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::water_msgs::ShipState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::water_msgs::ShipState_<ContainerAllocator1> & lhs, const ::water_msgs::ShipState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.modelstate == rhs.modelstate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::water_msgs::ShipState_<ContainerAllocator1> & lhs, const ::water_msgs::ShipState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace water_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::water_msgs::ShipState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::water_msgs::ShipState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::water_msgs::ShipState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::water_msgs::ShipState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::water_msgs::ShipState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::water_msgs::ShipState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::water_msgs::ShipState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33096c68969bd500c544dae60549ddbb";
  }

  static const char* value(const ::water_msgs::ShipState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33096c68969bd500ULL;
  static const uint64_t static_value2 = 0xc544dae60549ddbbULL;
};

template<class ContainerAllocator>
struct DataType< ::water_msgs::ShipState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "water_msgs/ShipState";
  }

  static const char* value(const ::water_msgs::ShipState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::water_msgs::ShipState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"gazebo_msgs/ModelState modelstate\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: gazebo_msgs/ModelState\n"
"# Set Gazebo Model pose and twist\n"
"string model_name           # model to set state (pose and twist)\n"
"geometry_msgs/Pose pose     # desired pose in reference frame\n"
"geometry_msgs/Twist twist   # desired twist in reference frame\n"
"string reference_frame      # set pose/twist relative to the frame of this entity (Body/Model)\n"
"                            # leave empty or \"world\" or \"map\" defaults to world-frame\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::water_msgs::ShipState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::water_msgs::ShipState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.modelstate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShipState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::water_msgs::ShipState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::water_msgs::ShipState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "modelstate: ";
    s << std::endl;
    Printer< ::gazebo_msgs::ModelState_<ContainerAllocator> >::stream(s, indent + "  ", v.modelstate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WATER_MSGS_MESSAGE_SHIPSTATE_H
